### ISSUE TITLE
'SplitTableBatchedEmbeddingBagsCodegen' object has no attribute 'get_learning_rate' when upgrading to 1.2.0

### ISSUE THREAD

**Issue by lneves-sc** [meta-pytorch/torchrec#3099]
Hey team, we have a working pipeline that uses torchrec 1.1.0. When we bump the version to 1.2.0, we are getting the following error (removed path prefixes):
```
  File "sharded_sparse_and_dense_sequence_module.py", line 202, in _configure_model
    self.model = DistributedModelParallel(
  File "torchrec/distributed/model_parallel.py", line 279, in __init__
    self._dmp_wrapped_module: nn.Module = self._init_dmp(module)
  File "torchrec/distributed/model_parallel.py", line 344, in _init_dmp
    return self._shard_modules_impl(module)
  File "torchrec/distributed/model_parallel.py", line 392, in _shard_modules_impl
    child = self._shard_modules_impl(
  File "torchrec/distributed/model_parallel.py", line 392, in _shard_modules_impl
    child = self._shard_modules_impl(
  File "torchrec/distributed/model_parallel.py", line 392, in _shard_modules_impl
    child = self._shard_modules_impl(
  File "torchrec/distributed/model_parallel.py", line 382, in _shard_modules_impl
    module = self._sharder_map[sharder_key].shard(
  File "torchrec/distributed/embedding.py", line 1434, in shard
    return ShardedEmbeddingCollection(
  File "torchrec/distributed/embedding.py", line 451, in __init__
    self._create_lookups()
  File "torchrec/distributed/embedding.py", line 1130, in _create_lookups
    self._lookups.append(sharding.create_lookup())
  File "torchrec/distributed/sharding/rw_sequence_sharding.py", line 147, in create_lookup
    return GroupedEmbeddingsLookup(
  File "torchrec/distributed/embedding_lookup.py", line 188, in __init__
    self._emb_modules.append(self._create_embedding_kernel(config, pg, device))
  File "torchrec/distributed/embedding_lookup.py", line 226, in _create_embedding_kernel
    return BatchedFusedEmbedding(
  File "torchrec/distributed/batched_embedding_kernel.py", line 1086, in __init__
    self._optim: EmbeddingFusedOptimizer = EmbeddingFusedOptimizer(
  File "torchrec/distributed/batched_embedding_kernel.py", line 386, in __init__
    "lr": emb_module.get_learning_rate(),
  File "torch/nn/modules/module.py", line 1928, in __getattr__
    raise AttributeError(
AttributeError: 'SplitTableBatchedEmbeddingBagsCodegen' object has no attribute 'get_learning_rate'
```
this is running with PyTorch 2.6.0 but I get the same error if I bump it to 2.7.0. FBGEMM-GPU version is 1.1.0 as 1.2.0 gives import errors.

Any changes on how we should be instantiating the DMPs?

**Comment by TroyGarden** [comment]
I believe this is due to the fbgemm-gpu version mismatch: the torchrec version sync with fbgemm-gpu, which is v1.2.0 in your case. you'll have to somehow update fbgemm-gpu to v1.2.0 or roll back to v1.1.0 for torchrec. 
you might try manually revert #2832 to work around this specific issue, but there could be other issue showing up.

**Comment by TroyGarden** [comment]
close this issue since there's very little can be done from torchrec side, feel free to reopen it or comment/ask questions if needed.
