### ISSUE TITLE
installing stable torchrec is not working

### ISSUE THREAD

**Issue by vkuzo** [meta-pytorch/torchrec#770]
I'm trying to follow https://github.com/pytorch/torchrec#installation to install torchrec, in particular:

```
# create new env
with-proxy conda create --name pytorch_torchrec_dlrm
conda activate pytorch_torchrec_dlrm

# install dependencies
with-proxy conda install pytorch cudatoolkit=11.5 -c pytorch -c conda-forge

# install torchrec
with-proxy pip install torchrec

# hello world
python
>>> import torchrec
...
  File "/home/vasiliy/local/miniconda3/envs/pytorch_torchrec_dlrm/lib/python3.10/site-packages/torch/_ops.py", 
line 505, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

# full trace: https://gist.github.com/vkuzo/e4e4608f34d090f3e935632fd644b0b9
```

I got the same error when trying to install torchrec against a locally built PyTorch master (1.14.x).  Is this a KP?  Any suggested workarounds?

**Comment by colin2328** [comment]
@vkuzo we've tested the new (0.3.0) torchrec with the new pytorch (1.13) and it works on our side.

Are you installing locally build pytorch? it looks like you are installing via conda
with-proxy conda install pytorch cudatoolkit=11.5 -c pytorch -c conda-forge

**Comment by vkuzo** [comment]
I see the same error whether I install torchrec against local PyTorch (v1.14.x) or a conda installation of PyTorch (v1.13.0).

Do you think trying to locally build torchrec would help?

I also see `jagged_2d_to_dense` existing in fbgemm master, maybe it's some kind of version mismatch with torchrec + fbgemm?

**Comment by colin2328** [comment]
@vkuzo , I can't repro your issue. When using locally built pytorch or the latest torch, I'm able to use and import torchrec fine. 
can you check which fbgemm-gpu you are using? (try showing pip list)?

Can you try 
>>> import fbgemm_gpu
>>> import torch
>>> torch.ops.jagged_2d_to_dense
<module 'torch.ops.jagged_2d_to_dense' from 'torch.ops'>

**Comment by vkuzo** [comment]
Thanks for helping!

Here is the output of running pip list and trying to run your code snippet: https://gist.github.com/vkuzo/9f1994f813803b31ed1078d20a27d34a

```
(pytorch_torchrec_dlrm) [vasiliy@devgpu032.ftw6 ~]$ pip list | grep fbgemm-gpu
fbgemm-gpu         0.3.0
(pytorch_torchrec_dlrm) [vasiliy@devgpu032.ftw6 ~]$ python
>>> import fbgemm_gpu
libc10_cuda.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/vasiliy/local/miniconda3/envs/pytorch_torchrec_dlrm/lib/python3.10/site-packages/torch/_ops.py", 
...
  File "/home/vasiliy/local/miniconda3/envs/pytorch_torchrec_dlrm/lib/python3.10/site-packages/fbgemm_gpu/_fbge
mm_gpu_docs.py", line 18, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/home/vasiliy/local/miniconda3/envs/pytorch_torchrec_dlrm/lib/python3.10/site-packages/torch/_ops.py", 
line 505, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense
```

**Comment by colin2328** [comment]
@vkuzo got it, thanks

it looks like this is an issue with fbgemm_gpu, do you mind creating an issue https://github.com/pytorch/FBGEMM/issues

It also looks like you're pip installing on an internal devgpu, Is it possible that the environment isn't clean?

**Comment by vkuzo** [comment]
> It also looks like you're pip installing on an internal devgpu, Is it possible that the environment isn't clean?

Yes, devgpus are the wild west.  I did create a fresh conda environment for this torchrec installation, but something system wide could definitely be messed up.  I verified that the pip command I used was conda's pip, which installs things locally to the active conda env.

FWIW, I unblocked myself today by doing the following:

```
# install cuda 11.7 (previously the system had 11.0, 11.4, 11.5)
with-proxy conda install cudatoolkit=11.7 -c nvidia
# install pytorch nightly for cuda 11.y7
with-proxy conda install pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
# verify pytorch is working with cuda 11.7 by inspecting env logs and looking for cuda
python -m torch.utils.collect_env
# reinstalling fbgemm-gpu didn't work, so I built it from source
with-proxy pip uninstall fbgemm_gpu
with-proxy git clone --recursive https://github.com/pytorch/FBGEMM.git
cd FBGEMM/fbgemm_gpu
with-proxy python setup.py develop
# interestingly, the version displayed was 0.1.1, which is lower than the official v0.3.0
Processing dependencies for fbgemm-gpu==0.1.1
Finished processing dependencies for fbgemm-gpu==0.1.1

# test, now it works
python
>>> import fbgemm_gpu
```

With the evidence above, I'd guess that the original problem could have been due to:
a. the nightly pytorch I was using was cpu only (because conda didn't have a pytorch with cuda for cuda v11.0|v11.4|v11.5).  Still not sure why it didn't work for locally built pytorch, since that was compiled with cuda v11.4.
b. perhaps something in fbgemm doesn't support cuda v11.4

Thanks for helping debug, closing this since it looks like it's related to fbgemm and not torchrec
