### ISSUE TITLE
AttributeError: 'OptimizerArgs' object has no attribute 'learning_rate'

### ISSUE THREAD

**Issue by YuandongXu-hotstar** [meta-pytorch/torchrec#2953]
I ran the example on torchrec-1.1.0-cpu env, and met an error. How to resolve it? Can anyone help?

``
#
def main_process(rank, world_size, master_addr, master_port):
    args = Args()
    # Some preliminary torch setup
    torch.jit._state.disable()
    device = torch.device("cpu") 
    backend = "gloo"

    # Starting mlflow
    os.environ["RANK"] = str(rank)
    os.environ["WORLD_SIZE"] = str(world_size)
    os.environ["MASTER_ADDR"] = master_addr
    os.environ["MASTER_PORT"] = str(master_port)
    os.environ['DATABRICKS_HOST'] = db_host
    os.environ['DATABRICKS_TOKEN'] = db_token

    # Saving parameters to mlflow
    if rank == 0:
        while mlflow.active_run():
            print("shut down mlflow previous run")
            mlflow.end_run()

        with mlflow.start_run():
            param_dict = get_relevant_fields(args, dense_cols, cat_cols, emb_counts)
            mlflow.log_params(param_dict, synchronous=True)

    # Straing distributed process group
    if not dist.is_initialized():
        print(f"Rank {rank} initializing process group")
        dist.init_process_group(backend=backend, world_size=world_size, rank=rank) 
    print(f"Rank {rank} initialized process group")

    # Loading the data
    from streaming.base.util import clean_stale_shared_memory
    clean_stale_shared_memory()
    train_dataloader = get_dataloader_with_mosaic(input_dir_train, args.batch_size, "train")
    val_dataloader = get_dataloader_with_mosaic(input_dir_validation, args.batch_size, "val")
    test_dataloader = get_dataloader_with_mosaic(input_dir_test, args.batch_size, "test")

    # Creating the embedding tables
    eb_configs = [
        EmbeddingBagConfig(
            name=f"t_{feature_name}",
            embedding_dim=args.embedding_dim,
            num_embeddings=4096,
            feature_names=[feature_name]
        )
        for feature_name in cat_cols
    ]

    # Creating the DLRM model
    dlrm_model = DLRM(
            embedding_bag_collection=EmbeddingBagCollection(tables=eb_configs, device=torch.device("cpu")),
            dense_in_features=len(dense_cols),
            dense_arch_layer_sizes=args.dense_arch_layer_sizes,
            over_arch_layer_sizes=args.over_arch_layer_sizes,
            dense_device=device,
        )

    train_model = DLRMTrain(dlrm_model)

    # Setting up the optimizer
    embedding_optimizer = torch.optim.Adagrad
    optimizer_kwargs = {"lr": args.learning_rate, "eps": args.eps}

    apply_optimizer_in_backward(
        embedding_optimizer,
        train_model.model.sparse_arch.parameters(),
        optimizer_kwargs,
    )

    planner = EmbeddingShardingPlanner(
        topology=Topology(
            local_world_size=1, #get_local_size(),
            world_size=dist.get_world_size(),
            compute_device=device.type,
        ),
        batch_size=args.batch_size,
        storage_reservation=HeuristicalStorageReservation(percentage=0.2),
    )

    plan = planner.collective_plan(
        train_model, 
        get_default_sharders(), 
        dist.GroupMember.WORLD
    )
    model = DistributedModelParallel(
        module=train_model,
        device=device,
        plan=plan
    ).to(device)

    log_state_dict_to_mlflow(model.module, artifact_path="model_state_dict_base")

    # Printing out the sharding information to see how the embedding tables are sharded across the GPUs
    if rank == 0 and args.print_sharding_plan:
        for collectionkey, plans in model._plan.plan.items():
            print(collectionkey)
            for table_name, plan in plans.items():
                print(table_name, "\n", plan, "\n")

    # Creating the optimizer for the distributed model
    def optimizer_with_params():
        return lambda params: torch.optim.Adagrad(params, lr=args.learning_rate, eps=args.eps)

    dense_optimizer = KeyedOptimizerWrapper(
        dict(in_backward_optimizer_filter(model.named_parameters())),
        optimizer_with_params(),
    )
    optimizer = CombinedOptimizer([model.fused_optimizer, dense_optimizer])
    lr_scheduler = LRPolicyScheduler(
        optimizer, args.lr_warmup_steps, args.lr_decay_start, args.lr_decay_steps
    )

    # Starting the training loop
    results = train_val_test(
        args,
        model,
        optimizer,
        device,
        train_dataloader,
        val_dataloader,
        test_dataloader,
        lr_scheduler,
    )

    # Destroying the process group
    dist.destroy_process_group()

master_addr = "127.0.0.1" 
master_port = 29501
main_process(0, 1, master_addr, master_port)

``

--------------------------------------------------------------------------------------------------------------
**It occurs an error as the following:**
``

--> 127 model = DistributedModelParallel(
    128     module=train_model,
    129     device=device,
    130     plan=plan
    131 ).to(device)
    133 log_state_dict_to_mlflow(model.module, artifact_path="model_state_dict_base")
    136 # Printing out the sharding information to see how the embedding tables are sharded across the GPUs

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:278, in DistributedModelParallel.__init__(self, module, env, device, plan, sharders, init_data_parallel, init_parameters, data_parallel_wrapper)
    276         plan = planner.plan(module, sharders)
    277 self._plan: ShardingPlan = plan
--> 278 self._dmp_wrapped_module: nn.Module = self._init_dmp(module)
    279 self._optim: CombinedOptimizer = self._init_optim(self._dmp_wrapped_module)
    281 if init_parameters:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:343, in DistributedModelParallel._init_dmp(self, module)
    342 def _init_dmp(self, module: nn.Module) -> nn.Module:
--> 343     return self._shard_modules_impl(module)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:391, in DistributedModelParallel._shard_modules_impl(self, module, path)
    388     return module
    390 for name, child in module.named_children():
--> 391     child = self._shard_modules_impl(
    392         child,
    393         path + "." + name if path else name,
    394     )
    395     setattr(module, name, child)
    397 return module

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:391, in DistributedModelParallel._shard_modules_impl(self, module, path)
    388     return module
    390 for name, child in module.named_children():
--> 391     child = self._shard_modules_impl(
    392         child,
    393         path + "." + name if path else name,
    394     )
    395     setattr(module, name, child)
    397 return module

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:391, in DistributedModelParallel._shard_modules_impl(self, module, path)
    388     return module
    390 for name, child in module.named_children():
--> 391     child = self._shard_modules_impl(
    392         child,
    393         path + "." + name if path else name,
    394     )
    395     setattr(module, name, child)
    397 return module

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py:381, in DistributedModelParallel._shard_modules_impl(self, module, path)
    379 if module_sharding_plan:
    380     sharder_key = type(module)
--> 381     module = self._sharder_map[sharder_key].shard(
    382         module,
    383         module_sharding_plan,
    384         self._env,
    385         self.device,
    386         path,
    387     )
    388     return module
    390 for name, child in module.named_children():

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py:1397, in EmbeddingBagCollectionSharder.shard(self, module, params, env, device, module_fqn)
   1389 def shard(
   1390     self,
   1391     module: EmbeddingBagCollection,
   (...)
   1395     module_fqn: Optional[str] = None,
   1396 ) -> ShardedEmbeddingBagCollection:
-> 1397     return ShardedEmbeddingBagCollection(
   1398         module=module,
   1399         table_name_to_parameter_sharding=params,
   1400         env=env,
   1401         fused_params=self.fused_params,
   1402         device=device,
   1403         qcomm_codecs_registry=self.qcomm_codecs_registry,
   1404         module_fqn=module_fqn,
   1405     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py:648, in ShardedEmbeddingBagCollection.__init__(self, module, table_name_to_parameter_sharding, env, fused_params, device, qcomm_codecs_registry, module_fqn)
    646 self._input_dists: List[nn.Module] = []
    647 self._lookups: List[nn.Module] = []
--> 648 self._create_lookups()
    649 self._output_dists: List[nn.Module] = []
    650 self._embedding_names: List[str] = []

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py:1135, in ShardedEmbeddingBagCollection._create_lookups(self)
   1131 def _create_lookups(
   1132     self,
   1133 ) -> None:
   1134     for sharding in self._embedding_shardings:
-> 1135         self._lookups.append(sharding.create_lookup())

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/sharding/tw_sharding.py:428, in TwPooledEmbeddingSharding.create_lookup(self, device, fused_params, feature_processor)
    422 def create_lookup(
    423     self,
    424     device: Optional[torch.device] = None,
    425     fused_params: Optional[Dict[str, Any]] = None,
    426     feature_processor: Optional[BaseGroupedFeatureProcessor] = None,
    427 ) -> BaseEmbeddingLookup:
--> 428     return GroupedPooledEmbeddingsLookup(
    429         grouped_configs=self._grouped_embedding_configs,
    430         pg=self._pg,
    431         device=device if device is not None else self._device,
    432         feature_processor=feature_processor,
    433     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/embedding_lookup.py:449, in GroupedPooledEmbeddingsLookup.__init__(self, grouped_configs, device, pg, feature_processor, scale_weight_gradients, sharding_type)
    447 self._emb_modules: nn.ModuleList = nn.ModuleList()
    448 for config in grouped_configs:
--> 449     self._emb_modules.append(_create_lookup(config, device, sharding_type))
    451 self._feature_splits: List[int] = []
    452 for config in grouped_configs:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/embedding_lookup.py:426, in GroupedPooledEmbeddingsLookup.__init__.<locals>._create_lookup(config, device, sharding_type)
    419     return BatchedDenseEmbeddingBag(
    420         config=config,
    421         pg=pg,
    422         device=device,
    423         sharding_type=sharding_type,
    424     )
    425 elif config.compute_kernel == EmbeddingComputeKernel.FUSED:
--> 426     return BatchedFusedEmbeddingBag(
    427         config=config,
    428         pg=pg,
    429         device=device,
    430         sharding_type=sharding_type,
    431     )
    432 elif config.compute_kernel in {
    433     EmbeddingComputeKernel.KEY_VALUE,
    434 }:
    435     return KeyValueEmbeddingBag(
    436         config=config,
    437         pg=pg,
    438         device=device,
    439         sharding_type=sharding_type,
    440     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/batched_embedding_kernel.py:1561, in BatchedFusedEmbeddingBag.__init__(self, config, pg, device, sharding_type)
   1547     fused_params["cache_precision"] = weights_precision
   1548 self._emb_module: SplitTableBatchedEmbeddingBagsCodegen = (
   1549     SplitTableBatchedEmbeddingBagsCodegen(
   1550         embedding_specs=list(
   (...)
   1559     )
   1560 )
-> 1561 self._optim: EmbeddingFusedOptimizer = EmbeddingFusedOptimizer(
   1562     config,
   1563     self._emb_module,
   1564     pg,
   1565 )
   1566 self._param_per_table: Dict[str, TableBatchedEmbeddingSlice] = dict(
   1567     _gen_named_parameters_by_table_fused(
   1568         emb_module=self._emb_module,
   (...)
   1572     )
   1573 )
   1574 self.init_parameters()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e5279890-8cdf-428b-bc73-4cbed5d22769/lib/python3.9/site-packages/torchrec/distributed/batched_embedding_kernel.py:385, in EmbeddingFusedOptimizer.__init__(self, config, emb_module, pg, create_for_table, param_weight_for_table)
    381 # pyre-ignore [33]
    382 state: Dict[Any, Any] = {}
    383 param_group: Dict[str, Any] = {
    384     "params": [],
--> 385     "lr": emb_module.optimizer_args.learning_rate,
    386 }
    388 params: Dict[str, Union[torch.Tensor, ShardedTensor]] = {}
    390 # Fused optimizers use buffers (they don't use autograd) and we want to make sure
    391 # that state_dict look identical to no-fused version.

AttributeError: 'OptimizerArgs' object has no attribute 'learning_rate'
``

>

**Comment by s1752729916** [comment]
I encountered the same problem, how did you solve it?

**Comment by xuyuandong** [comment]
> I encountered the same problem, how did you solve it?

reinstall the torch version

**Comment by rd-florian-pause** [comment]
I am facing the same issue but reinstalling did not fix the issue for me. What torch version are you using?

**Comment by rensilin** [comment]
> I am facing the same issue but reinstalling did not fix the issue for me. What torch version are you using?

[fbgemm_gpu 1.2.0](https://github.com/pytorch/FBGEMM/pull/3821/files#diff-9f3d32cc51331c006403a25b671b93e00215a0d4015bcee8a24aeb0c380b73db) has removed `learning_rate `
It works with `torch==2.6.0 fbgemm_gpu==1.1.0 torchrec==1.1.0`
